spring:
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:mariadb://localhost:3306/greengram2024_v2
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_tdd
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 5MB  # 이거 안해주면 디폴트가 1메가임, 20메가까지는 문제 없을거임
      max-request-size: 30MB

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
  cache:
    disabled: true

file:
  dir: D:\Students\MJ\download\greengram_tdd\  # 파일 업로드 시작 위치

app:  # 커스텀임 이름 안중요함
  jwt:
    secret: DaeguGreenArtAcademyClass502 # jwt 만들때 사용하는 열솨(암호화) > 나중애 복호화할때도 사용
    header-schema-name: authorization # 프론트-백 간 jwt 받는 헤더 키 이름
    token-type: Bearer # Bearer : JWT OR 0Auth (소셜로그인 떄 사용)를 의미
    access-token-expiry: 1800000 # AT - 만료시간 (ms) (30분)
    refresh-token-expiry: 1296000000 # RT - 만료시간 - 15일


---

spring:
  config:
    activate:
      on-profile: tdd # 프로필 이름 안쓰면 디폴트
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_tdd_test
  sql:
    init:
      mode: always

file:
  dir: D:\Students\MJ\download\greengram_tdd_test\