spring:
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:mariadb://localhost:3306/greengram2024_v2
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_v2
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 5MB  # 이거 안해주면 디폴트가 1메가임, 20메가까지는 문제 없을거임

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
  cache:
    disabled: true

file:
  dir: D:\Students\MJ\download\greengram_ver2\  # 파일 업로드 시작 위치

---

spring:
  config:
    activate:
      on-profile: test

file:
  dir: D:\Students\MJ\download\greengram_ver2_1\